management:
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: false
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true

# logging
logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
#    root: error
    org.hibernate.SQL: error
#    org.hibernate.type.descriptor.sql: trace

server:
  servlet:
    contextPath: /WSSeguro

integra:
  tipo:
    name: w2i
    
h2:
  url:
    name: ${h2.tcp.data:jdbc:h2:file:/usr/local/data/h2}
