management:
  endpoint:
    beans:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: false
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true

server:
  servlet:
    contextPath: /wsdl-prototype
